---
title: "Inversion pública 2006-2022"
subtitle: "Maestría en Ciencia de Datos"
author: |
  | Docente: 
  | MSc. Alvaro Limber Chirino Gutierrez
date: |
  | Maestrantes: 
  | - Ada Milenka Cueto Callisaya
  | - Alexander Ernesto Sucre Casas
  | 
  | Noviembre, 2023
output: pdf_document
csl: apa.csl
bibliography: referencias.bib
lang: es-ES
toc: TRUE
---

\pagebreak
# Introducción

La importancia de la inversión pública, radica en que la adecuada asignación de esta permite el crecimiento de los distintos sectores económico productivos, mediante la canalización de dichos recursos vía las diversas entidades de la *Administración Central*, *Instituciones descentralizadas*, *Gobernaciones*, *Municipalidades*, *Instituciones de Seguridad Social*, *Empresas públicas*, *Instituciones públicas financieras* y *Universidades*.

El presente trabajo presenta el tratamiento de una base de datos, presentando información relevante respecto al cumplimiento de la asignación presupuestaria.

# Objetivos

## Objetivos generales

El objetivo es brindar una herramienta eficaz para el análisis y seguimiento de la inversión pública, facilitando la toma de decisiones informadas y estratégicas en políticas gubernamentales y gestión económica a través del desarrollo de un dashboard integral que concentre y presente de manera visual los indicadores clave de la inversión pública en Bolivia. Este proporcionará una plataforma interactiva que permita visualizar de manera clara y accesible los principales datos sobre asignación presupuestaria, ejecución de recursos, distribución por sectores, regiones o entidades, y otros indicadores relevantes.

## Objetivos específicos

Obtener indicadores de asignación presupuestaria y su ejecución, desde distintos puntos de vista.

* Obtener indicadores detallados de asignación presupuestaria: Recopilar datos exhaustivos que describan cómo se asignan los recursos públicos a través de distintas entidades y sectores, brindando una visión amplia de la distribución de fondos.
* Analizar la ejecución presupuestaria desde múltiples perspectivas: Evaluar la efectividad y el grado de cumplimiento de la ejecución presupuestaria, considerando variables como el cumplimiento de metas, el seguimiento de programas específicos y el uso efectivo de los recursos asignados.
* Examinar la eficiencia en la asignación de recursos: Valorar la eficiencia en la utilización de los recursos asignados, identificando posibles desviaciones entre la asignación planificada y la ejecución real, y evaluando su impacto en los resultados obtenidos.
* Generar indicadores comparativos: Desarrollar indicadores comparativos que permitan evaluar y contrastar la asignación y ejecución presupuestaria entre distintos sectores, regiones o períodos temporales para identificar tendencias o áreas de mejora potencial.
* Proporcionar información integral para la toma de decisiones: Recopilar datos y generar análisis que sirvan como base sólida para la toma de decisiones informadas en políticas públicas, ofreciendo recomendaciones para mejorar la asignación y ejecución eficiente de los recursos públicos.

# Motivación

Poder obtener diversos resultados, mediante la aplicación del software R y sus diversas librerías, demostrando lo útil de uso de recursos tecnológicos para generar información relevante.

# Marco teórico

- Inversión pública. Todo gasto de recursos de origen público destinado a incrementar, mejorar o reponer las existencias de capital físico de dominio público y/o de capital humano, con el objeto de ampliar la capacidad del país para la prestación de servicios o producción de bienes.[@invpub]
- Fuentes de financiamiento para la Inversión Pública. Se identifican las siguientes fuentes de financiamiento para los proyectos de inversión pública[@fuenfin]:
  a) Recursos del Tesoro General de la Nación: Administrados por el Gobierno Central que se transfieren a las entidades de la Administración Central y al Fondo Compensatorio de Regalías, para financiar el Presupuesto de Inversión Pública.
  b) Recursos Específicos de las Entidades Públicas: Son recursos que se perciben y administran directamente por las
entidades públicas y se utilizan para financiar sus Presupuestos de Inversión Pública y que deben ser incorporados en el PGN.
  c) Recursos Externos: Son recursos que el Organo Rector del SNIP contrata de Organismos Financieros Multilaterales, Agencias de Cooperación Internacional y
Gobiernos, mediante convenios de crédito o donación, y que se transfieren a las entidades del sector público para financiar el Programa de Inversión Pública.
- Asignación presupuestaria es un intrumento que permite planificar, organizar, dirigir y controlar cada uno de los recursos del Estado, el mismo debe cumplirse de manera obligatoria con el fin de gestionar y programar los ingresos y egresos para el adecuado financiamiento público[@asigpresup].
- Proyecto. Tiene como objetivo la producción de bienes y servicios destinados a la satisfacción de una necesidad[@proyect].

# Descripción de la base de datos

Datos que detallan el *presupuesto asignado* y la *ejecución presupuestaria* de las diversas entidades dependientes de la Administración Central.

Las variables consideradas son las siguientes:

| Nro. | Variable              | Descripción                                                                   |   Tipo   |
|:----:|-----------------------|-------------------------------------------------------------------------------|:--------:|
|   1  | gestion               | El año del proyecto                                                           | Cadena   |
|   2  | periodo               | Dos periodos: Primer periodo gestiones 2006-2013, Segundo periodo gestiones 2014-2022| Cadena   |
|   3  | sector                | Sector económico, productivo u otra denominación                              | Cadena   |
|   4  | tipo_sector           | Sector social, productivo, multisectorial e infraestructura                   | Cadena   |
|   5  | depto                 | Departamento del proyecto, NACIONAL en caso de que sea de beneficio general   | Cadena   |
|   6  | region                | Región: Altiplano, Valle, Llano y Nacional                                    | Cadena   |
|   7  | provincia             | Provincia en la que se realizó el proyecto                                    | Cadena   |
|   8  | tipo_proyecto         | Ámbito de aplicación del proyecto                                             | Cadena   |
|   9  | entidad               | Entidad responsable del proyecto y que recibió los recursos para su ejecución | Cadena   |
|  10  | tipo_entidad_ agrupado | Tipo de entidad agrupada por rubro                                            | Cadena   |
|  11  | sigla_entidad         | Sigla de la entidad                                                           | Cadena   |
|  12  | tipo_recurso          | Si la fuente de financiamiento es interna o externa                           | Cadena   |
|  13  | tipo_entidad          | Tipo de entidad según su rol a nivel nacional                                 | Cadena   |
|  14  | tipo_financiamiento   | Tipo de financiamiento, fuente de los recursos                                | Cadena   |
|  15  | Presupuesto_inicial   | Presupuesto asignado inicialmente                                             | Numérico |
|  16  | presupuesto_vigente   | Presupuesto vigente                                                           | Numérico |
|  17  | presupuesto_ ejecutado | Presupuesto ejecutado                                                         | Numérico |

# Metodología

## 1. Indicadores y fichas de indicadores

|INDICADOR 1|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado|
|Interpretación|Cuanto se ejecutó en relación a lo programado por año|
|Método de cálculo|Ninguo|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 2|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por sector económico|
|Interpretación|Cuanto se ejecutó en relación a lo programado por año y sector económico|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 3|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO, % DE EJECUCIÓN (ESTRUCTURA DEL PRESUPUESTO)|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por sector económico y porcentaje de ejecución|
|Interpretación|Porcentaje de ejecución de lo programado por año y sector económico|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 4|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO, % DE EJECUCIÓN POR REGIÓN|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por región y porcentaje de ejecución|
|Interpretación|Porcentaje de ejecución de lo programado por año y región|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 5|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO, % DE EJECUCIÓN POR DEPARTAMENTO|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por departamento y porcentaje de ejecución|
|Interpretación|Porcentaje de ejecución de lo programado por año y departamento|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 6|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO, % DE EJECUCIÓN POR DEPARTAMENTO Y MUNICIPIO|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por departamento, municipio y porcentaje de ejecución|
|Interpretación|Porcentaje de ejecución de lo programado por año, departamento y municipio|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 7|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO, % DE EJECUCIÓN POR TIPO DE SECTOR Y TIPO DE PROYECTO|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por tipo de sector y tipo de proyecto|
|Interpretación|Porcentaje de ejecución de lo programado por año, tipo de sector y tipo de proyecto|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 8|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO, % DE EJECUCIÓN POR TIPO DE SECTOR Y TIPO DE PROYECTO|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por tipo de sector y tipo de proyecto|
|Interpretación|Porcentaje de ejecución de lo programado por año, tipo de sector y tipo de proyecto|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 9|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO, % DE EJECUCIÓN POR TIPO DE SECTOR Y SIGLA DE ENTIDAD|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por tipo de sector y sigla de la entidad|
|Interpretación|Porcentaje de ejecución de lo programado por año, tipo de sector y sigla de la entidad|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 10|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO, % DE EJECUCIÓN POR TIPO DE SECTOR Y TIPO DE ENTIDAD|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por tipo de sector y tipo de entidad|
|Interpretación|Porcentaje de ejecución de lo programado por año, tipo de sector y tipo de entidad|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 11|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO, % DE EJECUCIÓN POR TIPO DE SECTOR, TIPO DE RECURSO Y TIPO DE FINANCIAMIENTO|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por tipo de sector, tipo de recurso y tipo de financiamiento|
|Interpretación|Porcentaje de ejecución de lo programado por año, tipo de sector, tipo de recurso y tipo de financiamiento|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


|INDICADOR 12|PRESUPUESTO PROGRAMADO VS PRESUPUESTO EJECUTADO POR SECTOR ECONÓMICO, % DE EJECUCIÓN POR TIPO DE SECTOR Y DEPARTAMENTO|
|-----|-----|
|Definición|Se muestra el presupuesto programado en comparación al presupuesto ejecutado por tipo de sector y departamento|
|Interpretación|Porcentaje de ejecución de lo programado por año, tipo de sector y departamento|
|Método de cálculo|Ninguno|
|Fuente de cálculo|Base de datos de Asignación Presupuestaria|
|Periodicidad del reporte|Anual|
|Responsable|Viceministerio de Inversión Pública y Financiamiento Externo|


## 2. Tratamiento sobre la base de datos

La base de datos, compuesta por 160,795 registros, fue originalmente en formato Excel y posteriormente se convirtió a formato CSV para su procesamiento con SPARK, con resultados altamente satisfactorios. Esta conversión a CSV se llevó a cabo debido a que este formato es más eficiente para manejar grandes volúmenes de datos, resultando en tiempos de lectura y escritura más rápidos en comparación con Excel. Además, CSV es un formato más compatible y universal para su uso en diversas plataformas y herramientas de procesamiento de datos.
La elección de SPARK como herramienta de procesamiento se basó en su capacidad para manejar grandes conjuntos de datos de manera distribuida y escalable. SPARK está diseñado para trabajar con conjuntos de datos extensos de manera eficiente, aprovechando el procesamiento distribuido en clústeres, lo que permite realizar operaciones complejas en paralelo, acelerando significativamente el análisis y procesamiento de la información.
Es importante destacar que, a pesar de la magnitud de la base de datos, no fue necesario llevar a cabo ningún tratamiento adicional a los registros, lo que resalta la eficacia del proceso y la calidad de los datos iniciales para su análisis con SPARK.

## 3. Visualización de la información

Este proyecto se materializa a través de la visualización de un Dashboard, donde se emplean tres herramientas clave: ggplot, plotly y datatables en R.

-	**ggplot**: Es una biblioteca de visualización de datos en R que ofrece una gramática de gráficos, permitiendo la creación de representaciones visuales altamente personalizables. Su enfoque se basa en capas, lo que facilita la construcción de gráficos complejos a partir de componentes simples, brindando un control detallado sobre la estética y estructura de las visualizaciones.
-	**plotly**: Esta biblioteca permite crear gráficos interactivos en R. Ofrece una amplia gama de gráficos interactivos, desde scatter plots hasta gráficos 3D, que pueden ser manipulados y explorados directamente en el Dashboard. Esto añade una dimensión dinámica y de exploración a las visualizaciones, permitiendo a los usuarios interactuar con los datos.
-	**datatables**: Es una herramienta que facilita la visualización y manipulación de tablas en R, ofreciendo una amplia gama de funcionalidades para trabajar con datos tabulares. Su integración en el Dashboard permite mostrar y manejar conjuntos de datos de manera eficiente y dinámica, agregando capacidad de filtrado, ordenamiento y búsqueda a las tablas mostradas en la interfaz.

La combinación de estas herramientas en el Dashboard no solo posibilita la representación visual de los datos, sino que también facilita su exploración interactiva y su presentación de manera estructurada y amigable para el usuario final.

## 4. Armado de la plataforma

Los gráficos se crearon utilizando las bibliotecas Flexdashboard y tidyverse. Estas herramientas resultaron fundamentales, ya que permitieron no solo la generación de representaciones visuales, sino también un análisis de datos exhaustivo y eficiente. La combinación de Flexdashboard para la creación del dashboard interactivo y tidyverse para el procesamiento y visualización de datos aseguró una presentación detallada y dinámica de la información.

# Resultados y análisis

# Conclusiones y recomendaciones

# Referencias

